name: Compile Check (Windows)
on:
  push:
  pull_request:
env:
  CMakeVersion: 3.14.x
jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        vsg-tag: [master, VulkanSceneGraph-1.0]
        build-shared: [ON]
        vulkan-version: [1.3.224.1]

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: ${{ env.CMakeVersion }}
    - name: Install Vulkan SDK
      uses: humbletim/install-vulkan-sdk@v1.1.1
      with:
        version: ${{ matrix.vulkan-version }}
        cache: true
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Checkout vsg
      uses: actions/checkout@v3
      with:
        repository: vsg-dev/VulkanSceneGraph
        ref: ${{matrix.vsg-tag}}
        path: vsg
        submodules: true
    - name: Build and Install VSG
      shell: bash
      run: |
        cd vsg
        cmake --help
        cmake . -DBUILD_SHARED_LIBS=${{matrix.build-shared}} -A x64 -DCMAKE_INSTALL_PREFIX=../../install
        MSBuild.exe INSTALL.vcxproj -p:Configuration=Release
    - name: Build and Install VSGVR
      shell: bash
      run: |
        cmake . -DBUILD_SHARED_LIBS=${{matrix.build-shared}} -A x64 -DCMAKE_INSTALL_PREFIX=../install
        MSBuild.exe INSTALL.vcxproj -p:Configuration=Release
